name: OpenLogin - Tests

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  run-tests:
    name: Run OpenLogin - tests
    strategy:
      matrix:
        env: [prod, cyan]
        browser: [firefox, chromium]
        cloudBuild: [TorusE2ETests]
    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ matrix.env }}
    outputs:
      conclusion: ${{ steps.run-tests.conclusion }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        continue-on-error: true

      - id: run-tests
        name: "AWS CodeBuild run build"
        uses: aws-actions/aws-codebuild-run-build@v1.0.8
        with:
          project-name: ${{ matrix.cloudBuild }}
          buildspec-override: ./buildspec.yml
          env-vars-for-codebuild: |
            PLATFORM,
            MAILOSAUR_API_KEY,
            MAILOSAUR_SERVER_ID,
            MAILOSAUR_SERVER_DOMAIN
        env:
          PLATFORM: ${{ matrix.env }}
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
          MAILOSAUR_SERVER_ID: ${{ secrets.MAILOSAUR_SERVER_ID }}
          MAILOSAUR_SERVER_DOMAIN: ${{ secrets.MAILOSAUR_API_KEY }}

      - id: telegram-alert
        name: Alert to telegram channel
        if: always()
        run: |
          if [[ ${{ steps.run-tests.outcome }} != 'success' ]]
          then
              echo "Test Failed, sending telegram alert"
              curl "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage?chat_id=${{secrets.CHAT_ID}}&text=Homepage%0ATestresult=Failed%0AOS=${{matrix.os}}%0Abrowser=${{matrix.browser}}%0AEnvironment=${{matrix.env}}%0AJob=${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          else
              echo "Test Passed, no alert!"
          fi
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore

  update-status:
    name: Update OpenLogin - Homepage status
    needs: run-tests
    if: (success() || failure()) && (needs.run-tests.outputs.conclusion != 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        uses: fjogeleit/http-request-action@master
        with:
          url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.HOME_PAGE_COMPONENT_ID }}
          customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
          method: PATCH
          contentType: "application/json"
          timeout: 10000
          data: >-
            { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
