---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd /app
  build:
    commands:
      - echo Running Tests
      - chmod +x ./bin/*
      - ls
      - npm run test:trace
  post_build:
    commands:
      - echo Tests Complete
      - mv test-results openloginV3
      - cd ./openloginV4/test-results/
      - ls
artifacts:
  type: zip
  files:
    - ./**/*
  name: Web3auth-e2e-tests
  base-directory: /app
