---
name: OpenLogin - TorusE2ETests - CodeBuild
on:
  push:
    branches:
      - new_ui_openlogin
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: null
env:
  NODE_VERSION: 16
jobs:
  build:
    name: Run OpenLogin - tests
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - env:
              PLATFORM: aqua
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: web3auth-e2e-tests
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
      - name: Trigger Cloud Build
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ matrix.region }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: web3auth-e2e-tests
        run: >
          aws codebuild start-build --project-name TorusE2ETests --image-override $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA --environment-variables-override name=PLATFORM,value=${{ matrix.env.PLATFORM }},type=PLAINTEXT --buildspec-override buildspec.yml
