name: Lighthouse

on: push

env:
  NODE_VERSION: 14

jobs:
  run-lighthouse:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Setup
        run: |
          yarn install
          mkdir lighthouse

      - name: Run Lighthouse
        run: |
          yarn lighthouse https://tor.us --output-path lighthouse/tor.us.html --save-assets --chrome-flags="--headless"
          yarn lighthouse https://app.tor.us --output-path lighthouse/app.tor.us.html --save-assets --chrome-flags="--headless"
          yarn lighthouse https://app.openlogin.com --output-path lighthouse/app.openlogin.com.html --save-assets --chrome-flags="--headless"
          cd lighthouse
          tree -H '.' -L 1 --noreport --charset utf-8 -P "*.html" -o index.html

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          path: lighthouse
