name: Google Login

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

env:
  NODE_VERSION: 14
  FORCE_COLOR: 3

jobs:
  run-tests:
    name: Google Login tests
    strategy:
      matrix:
        include:
          - browser: chromium
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get Yarn cache directory
        id: get-yarn-cache-dir
        run: echo "::set-output name=path::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.get-yarn-cache-dir.outputs.path }}
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Install Ubuntu dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn run playwright install-deps ${{ matrix.browser }}

      - name: Run tests
        run: |
          yarn run playwright test --config google.config.ts --project ${{ matrix.browser }}

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore

  report-success:
    name: Google Login is alive
    needs: run-tests
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        uses: fjogeleit/http-request-action@master
        with:
          url: https://torusstatus.com/api/services/39
          bearerToken: ${{ secrets.STATUS_API_TOKEN }}
          method: POST
          data: >-
            {
              "online": true,
              "latency": 3000000,
              "issue": "NA"
            }

  report-failure:
    name: Google Login is down
    needs: run-tests
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        uses: fjogeleit/http-request-action@master
        with:
          url: https://torusstatus.com/api/services/39
          bearerToken: ${{ secrets.STATUS_API_TOKEN }}
          method: POST
          data: >-
            {
              "online": false,
              "latency": 3000000,
              "issue": "NA"
            }
