name: OpenLogin - Homepage- CYAN

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

env:
  NODE_VERSION: 16
  PLATFORM: CYAN

jobs:
  run-tests:
    name: Run OpenLogin - Homepage tests- CYAN
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        os: [macos-latest, windows-latest, ubuntu-latest]
        exclude:
          - browser: webkit
            os: windows-latest
          - browser: webkit
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    outputs:
      conclusion: ${{ steps.run-tests.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        continue-on-error: true

      - id: yarn-install
        name: Install Node.js dependencies
        if: steps.setup-node.outcome == 'success'
        run: yarn install --frozen-lockfile
        continue-on-error: true

      - id: yarn-install-deps
        name: Install Ubuntu dependencies
        if: steps.yarn-install.outcome == 'success' && startsWith(matrix.os, 'ubuntu')
        run: yarn run playwright install-deps ${{ matrix.browser }}
        continue-on-error: true

      - id: run-tests
        name: Run tests
        if: steps.yarn-install.outcome == 'success' && steps.yarn-install-deps.outcome != 'failure'
        run: yarn run playwright test --config openlogin/homepage/index.config.ts --project ${{ matrix.browser }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore

