name: OpenLogin - RunAll

on:
  push:
    branches:
      - sid-e2e-ci-pipe
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  run-tests:
    name: Run OpenLogin - E2E Tests
    strategy:
      matrix:
        env: [testing]
        browser: [firefox]
        os: [macos-latest]
        # include:
        #   - os: macos-latest
        #     browser: chromium
        #     env: cyan
        # - os: macos-latest
        #   browser: webkit
        #   env: beta
        # - os: macos-latest
        #   browser: webkit
        #   env: prod

    runs-on: ${{ matrix.os }}
    env:
      PLATFORM: ${{ matrix.env }}
      MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
      MAILOSAUR_SERVER_ID: ${{ secrets.MAILOSAUR_SERVER_ID }}
      MAILOSAUR_SERVER_DOMAIN: ${{ secrets.MAILOSAUR_API_KEY }}

    outputs:
      conclusion: ${{ steps.run-tests.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: setup-node
        name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        continue-on-error: true

      - id: yarn-install
        name: Install Node.js dependencies
        if: steps.setup-node.outcome == 'success'
        run: yarn install --frozen-lockfile
        continue-on-error: true

      - id: yarn-install-deps
        name: Install Ubuntu dependencies
        if: steps.yarn-install.outcome == 'success' && startsWith(matrix.os, 'ubuntu')
        run: yarn run playwright install-deps ${{ matrix.browser }}
        continue-on-error: true

      - id: run-tests
        name: Run All tests
        run: npx playwright test --browser=firefox --workers=1
