name: OpenLogin - Homepage

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

env:
  NODE_VERSION: 14
  STATUS_SERVICE_ID: 38

jobs:
  run-tests:
    name: Run OpenLogin - Homepage tests
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        os: [macos-latest, windows-latest, ubuntu-latest]
        exclude:
          - browser: webkit
            os: windows-latest
          - browser: webkit
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Install Ubuntu dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn run playwright install-deps ${{ matrix.browser }}

      - name: Run tests
        run: yarn run playwright test --config openlogin/homepage/index.config.ts --project ${{ matrix.browser }}

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore

  update-status:
    name: Update OpenLogin - Homepage status
    needs: run-tests
    if: ${{ success() || failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        uses: fjogeleit/http-request-action@master
        with:
          url: https://torusstatus.com/api/services/${{ env.STATUS_SERVICE_ID }}
          bearerToken: ${{ secrets.STATUS_API_TOKEN }}
          method: PATCH
          data: >-
            { "online": ${{ needs.run-tests.result == 'success' }} }
