name: OpenLogin - Google Login

on:
  push
  # schedule:
  #   - cron: "*/15 * * * *"
  # workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  run-tests:
    name: Run OpenLogin - Google Login tests
    strategy:
      matrix:
        local_path: [openlogin/login-with-google]
        os: [macos-latest]
        env: [PROD]
        browser: [chromium, webkit]
        include:
          - s3_path: openlogin/login-with-google
            env: PROD
          - s3_path: openlogin/login-with-google-cyan
            browser: webkit
            os: macos-latest
            env: CYAN
          - s3_path: openlogin/login-with-google-beta
            browser: chromium
            os: macos-latest
            env: STAGING

    runs-on: ${{ matrix.os }}
    env:
      PLATFORM: ${{ matrix.env }}
    outputs:
      conclusion: ${{ steps.run-tests.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        continue-on-error: true

      - id: yarn-install
        name: Install Node.js dependencies
        if: steps.setup-node.outcome == 'success'
        run: yarn install --frozen-lockfile
        continue-on-error: true

      - id: yarn-install-deps
        name: Install Ubuntu dependencies
        if: steps.yarn-install.outcome == 'success' && startsWith(matrix.os, 'ubuntu')
        run: yarn run playwright install-deps ${{ matrix.browser }}
        continue-on-error: true

      - id: configure-aws
        name: Configure AWS credentials
        if: steps.yarn-install.outcome == 'success' && steps.yarn-install-deps.outcome != 'failure'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        continue-on-error: true

      - id: download-state
        name: Download remote browser snapshots
        if: steps.configure-aws.outcome == 'success'
        run: aws s3 cp s3://torus-e2e-tests/${{ matrix.s3_path }}/ ${{ matrix.local_path }}/ --recursive
        continue-on-error: true

      - id: run-tests
        name: Run tests
        if: steps.download-state.outcome == 'success'
        run: yarn run playwright test --config ${{ matrix.local_path }}/index.config.ts --project ${{ matrix.browser }}

      - id: telegram-alert
        name: Alert to telegram channel
        if: steps.run-tests.outcome != 'success'
        run: curl "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage?chat_id=${{secrets.CHAT_ID}}&text=LoginWithGoogle%0ATestresult=Failed%0AOS=${{matrix.os}}%0Abrowser=${{matrix.browser}}"
        continue-on-error: true

      - id: upload-state
        name: Upload logged-in state once a week
        uses: ./.github/actions/upload-state/
        with:
          os: ${{ matrix.os }}
          browser: ${{ matrix.browser }}
          s3_path: ${{ matrix.s3_path }}
          local_path: ${{ matrix.local_path }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
        continue-on-error: true


      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore

  # update-status:
  #   name: Update OpenLogin - Google Login status
  #   needs: run-tests
  #   if: (success() || failure()) && (needs.run-tests.outputs.conclusion != 'skipped')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update status
  #       uses: fjogeleit/http-request-action@master
  #       with:
  #         url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.GOOGLE_COMPONENT_ID }}
  #         customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
  #         method: PATCH
  #         contentType: "application/json"
  #         timeout: 10000
  #         data: >-
  #           { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
