name: Tests

on:
  push:
    branches: [master]

env:
  NODE_VERSION: 14
  FORCE_COLOR: 3

jobs:
  run-all-tests:
    name: Run all tests
    strategy:
      matrix:
        include:
          - os: macos-10.15
            project: google-on-chrome
          - os: windows-2019
            project: google-on-chrome
          - os: ubuntu-20.04
            project: google-on-chrome
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get Yarn cache directory
        id: get-yarn-cache-dir
        run: echo "::set-output name=path::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.get-yarn-cache-dir.outputs.path }}
          key: "${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-\
            ${{ hashFiles('**/yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn install:system-deps

      - name: Run tests
        run: yarn test --project=${{ matrix.project }}

      - name: Upload test-results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/
