name: OpenLogin - TorusE2ETests - GitHub

on:
  push:
    branches:
      - new_ui_openlogin
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'prod|beta|cyan|staging|testing|celeste|local'
        required: true
        default: 'testing'

env:
  NODE_VERSION: 16

jobs:
  build:
    name: Run OpenLogin - tests
    strategy:
      matrix:
        include:
          - env:
              PLATFORM: prod
          - env:
              PLATFORM: aqua
    runs-on: macos-latest
    # env:
    #   PLATFORM: ${{ matrix.env }}
    # outputs:
    #   conclusion: ${{ steps.run-tests.conclusion }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Set env NEED
        run: echo ${{ github.event.action }}
      - name: Trigger tests
        env:
          FB_TEST_USER_EMAIL:	"jdnxqujvhk_1673407774@tfbnw.net"
          FB_TEST_USER_PASS:	"VerySecurePassword"
          FB_TEST_USER_NAME:	"Jennifer Alhiegffddbbg Brownman"
          GOOGLE_ACCOUNT:	"torus.e2e@gmail.com"
          GOOGLE_PASSWORD:	"VerySecurePassword@123"
          GOOGLE_NAME:	"torus"
          DISCORD_EMAIL:	"torus.e2e.tests@gmail.com"
          DISCORD_PASSWORD:	"VerySecurePassword@123"
          TWITTER_ACCOUNT:	"toruse2etests"
          TWITTER_PASSWORD:	"VerySecurePassword@123"
          TWITTER_EMAIL:	"torus.e2e.tests@gmail.com"
          CI:	true
          MAILOSAUR_API_KEY:	"M2B4hsIhbEJVT0uXH7OsyLwYLFu2JdyL"
          MAILOSAUR_SERVER_ID:	"zbvyh1nv"
          MAILOSAUR_SERVER_DOMAIN:	"zbvyh1nv.mailosaur.net"
          PLATFORM: ${{ matrix.env.PLATFORM }}
          APPVERSION: "v4"
          GITHUB_USER_EMAIL: "torus.e2e@gmail.com"
          GITHUB_USER_PASSWORD: "VerySecurePassword@123"
        run: |
          echo "Platform: ${{ matrix.env.PLATFORM }}" && ls && npm install && npx playwright install && npm run test:config

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: test-results/*
          if-no-files-found: ignore
